// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: calculatorpb/calculatorpb.proto

package calculatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SquareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number float32 `protobuf:"fixed32,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *SquareRequest) Reset() {
	*x = SquareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculatorpb_calculatorpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SquareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareRequest) ProtoMessage() {}

func (x *SquareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculatorpb_calculatorpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareRequest.ProtoReflect.Descriptor instead.
func (*SquareRequest) Descriptor() ([]byte, []int) {
	return file_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{0}
}

func (x *SquareRequest) GetNumber() float32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type SquareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SqrtResult float32 `protobuf:"fixed32,1,opt,name=sqrtResult,proto3" json:"sqrtResult,omitempty"`
}

func (x *SquareResponse) Reset() {
	*x = SquareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculatorpb_calculatorpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SquareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareResponse) ProtoMessage() {}

func (x *SquareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculatorpb_calculatorpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareResponse.ProtoReflect.Descriptor instead.
func (*SquareResponse) Descriptor() ([]byte, []int) {
	return file_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{1}
}

func (x *SquareResponse) GetSqrtResult() float32 {
	if x != nil {
		return x.SqrtResult
	}
	return 0
}

type PerfectNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PerfectNumberRequest) Reset() {
	*x = PerfectNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculatorpb_calculatorpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfectNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfectNumberRequest) ProtoMessage() {}

func (x *PerfectNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculatorpb_calculatorpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfectNumberRequest.ProtoReflect.Descriptor instead.
func (*PerfectNumberRequest) Descriptor() ([]byte, []int) {
	return file_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{2}
}

func (x *PerfectNumberRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PerfectNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PerfectNumber int64 `protobuf:"varint,1,opt,name=PerfectNumber,proto3" json:"PerfectNumber,omitempty"`
}

func (x *PerfectNumberResponse) Reset() {
	*x = PerfectNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculatorpb_calculatorpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfectNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfectNumberResponse) ProtoMessage() {}

func (x *PerfectNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculatorpb_calculatorpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfectNumberResponse.ProtoReflect.Descriptor instead.
func (*PerfectNumberResponse) Descriptor() ([]byte, []int) {
	return file_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{3}
}

func (x *PerfectNumberResponse) GetPerfectNumber() int64 {
	if x != nil {
		return x.PerfectNumber
	}
	return 0
}

type TotalNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number float64 `protobuf:"fixed64,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *TotalNumberRequest) Reset() {
	*x = TotalNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculatorpb_calculatorpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalNumberRequest) ProtoMessage() {}

func (x *TotalNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculatorpb_calculatorpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalNumberRequest.ProtoReflect.Descriptor instead.
func (*TotalNumberRequest) Descriptor() ([]byte, []int) {
	return file_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{4}
}

func (x *TotalNumberRequest) GetNumber() float64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type TotalNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalNumber float64 `protobuf:"fixed64,1,opt,name=TotalNumber,proto3" json:"TotalNumber,omitempty"`
}

func (x *TotalNumberResponse) Reset() {
	*x = TotalNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculatorpb_calculatorpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalNumberResponse) ProtoMessage() {}

func (x *TotalNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculatorpb_calculatorpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalNumberResponse.ProtoReflect.Descriptor instead.
func (*TotalNumberResponse) Descriptor() ([]byte, []int) {
	return file_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{5}
}

func (x *TotalNumberResponse) GetTotalNumber() float64 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

type FindMinimumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *FindMinimumRequest) Reset() {
	*x = FindMinimumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculatorpb_calculatorpb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindMinimumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMinimumRequest) ProtoMessage() {}

func (x *FindMinimumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculatorpb_calculatorpb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMinimumRequest.ProtoReflect.Descriptor instead.
func (*FindMinimumRequest) Descriptor() ([]byte, []int) {
	return file_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{6}
}

func (x *FindMinimumRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type FindMinimumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Minimum int32 `protobuf:"varint,1,opt,name=minimum,proto3" json:"minimum,omitempty"`
}

func (x *FindMinimumResponse) Reset() {
	*x = FindMinimumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculatorpb_calculatorpb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindMinimumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMinimumResponse) ProtoMessage() {}

func (x *FindMinimumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculatorpb_calculatorpb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMinimumResponse.ProtoReflect.Descriptor instead.
func (*FindMinimumResponse) Descriptor() ([]byte, []int) {
	return file_calculatorpb_calculatorpb_proto_rawDescGZIP(), []int{7}
}

func (x *FindMinimumResponse) GetMinimum() int32 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

var File_calculatorpb_calculatorpb_proto protoreflect.FileDescriptor

var file_calculatorpb_calculatorpb_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2f, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x27, 0x0a,
	0x0d, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x0e, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x71, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x73, 0x71,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2e, 0x0a, 0x14, 0x50, 0x65, 0x72, 0x66,
	0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3d, 0x0a, 0x15, 0x50, 0x65, 0x72, 0x66,
	0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x65, 0x72, 0x66, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x50, 0x65, 0x72, 0x66, 0x65, 0x63,
	0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x12, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x37, 0x0a, 0x13, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2c,
	0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x13,
	0x46, 0x69, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x32, 0xde, 0x02,
	0x0a, 0x11, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x6f, 0x6f,
	0x74, 0x12, 0x19, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53,
	0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x50, 0x65,
	0x72, 0x66, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x65, 0x63, 0x74,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x65,
	0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x52, 0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x54, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64,
	0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x1e, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1b,
	0x5a, 0x19, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2f, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_calculatorpb_calculatorpb_proto_rawDescOnce sync.Once
	file_calculatorpb_calculatorpb_proto_rawDescData = file_calculatorpb_calculatorpb_proto_rawDesc
)

func file_calculatorpb_calculatorpb_proto_rawDescGZIP() []byte {
	file_calculatorpb_calculatorpb_proto_rawDescOnce.Do(func() {
		file_calculatorpb_calculatorpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculatorpb_calculatorpb_proto_rawDescData)
	})
	return file_calculatorpb_calculatorpb_proto_rawDescData
}

var file_calculatorpb_calculatorpb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_calculatorpb_calculatorpb_proto_goTypes = []interface{}{
	(*SquareRequest)(nil),         // 0: calculator.SquareRequest
	(*SquareResponse)(nil),        // 1: calculator.SquareResponse
	(*PerfectNumberRequest)(nil),  // 2: calculator.PerfectNumberRequest
	(*PerfectNumberResponse)(nil), // 3: calculator.PerfectNumberResponse
	(*TotalNumberRequest)(nil),    // 4: calculator.TotalNumberRequest
	(*TotalNumberResponse)(nil),   // 5: calculator.TotalNumberResponse
	(*FindMinimumRequest)(nil),    // 6: calculator.FindMinimumRequest
	(*FindMinimumResponse)(nil),   // 7: calculator.FindMinimumResponse
}
var file_calculatorpb_calculatorpb_proto_depIdxs = []int32{
	0, // 0: calculator.CalculatorService.SquareRoot:input_type -> calculator.SquareRequest
	2, // 1: calculator.CalculatorService.PerfectNumber:input_type -> calculator.PerfectNumberRequest
	4, // 2: calculator.CalculatorService.TotalNumber:input_type -> calculator.TotalNumberRequest
	6, // 3: calculator.CalculatorService.FindMinimum:input_type -> calculator.FindMinimumRequest
	1, // 4: calculator.CalculatorService.SquareRoot:output_type -> calculator.SquareResponse
	3, // 5: calculator.CalculatorService.PerfectNumber:output_type -> calculator.PerfectNumberResponse
	5, // 6: calculator.CalculatorService.TotalNumber:output_type -> calculator.TotalNumberResponse
	7, // 7: calculator.CalculatorService.FindMinimum:output_type -> calculator.FindMinimumResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculatorpb_calculatorpb_proto_init() }
func file_calculatorpb_calculatorpb_proto_init() {
	if File_calculatorpb_calculatorpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculatorpb_calculatorpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SquareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculatorpb_calculatorpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SquareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculatorpb_calculatorpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerfectNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculatorpb_calculatorpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerfectNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculatorpb_calculatorpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculatorpb_calculatorpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculatorpb_calculatorpb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindMinimumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculatorpb_calculatorpb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindMinimumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculatorpb_calculatorpb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculatorpb_calculatorpb_proto_goTypes,
		DependencyIndexes: file_calculatorpb_calculatorpb_proto_depIdxs,
		MessageInfos:      file_calculatorpb_calculatorpb_proto_msgTypes,
	}.Build()
	File_calculatorpb_calculatorpb_proto = out.File
	file_calculatorpb_calculatorpb_proto_rawDesc = nil
	file_calculatorpb_calculatorpb_proto_goTypes = nil
	file_calculatorpb_calculatorpb_proto_depIdxs = nil
}
